export default [ 
    {
        id: '1',
        train: 'l',
        stations: [ 
                    '14th Street/Eighth Avenue station','14th Street/Sixth Avenue station',
                    '14 Street Union Square Station','Third Avenue station','First Avenue station',
                    'Bedford Avenue station','Metropolitan Avenue/Lorimer Street station',
                    'Graham Avenue station','Grand Street station',
                    'Montrose Avenue station','Morgan Avenue station',
                    'Jefferson Street station', 'DeKalb Avenue station',
                    'Myrtle–Wyckoff Avenues station', 'Halsey Street station',
                    'Wilson Avenue station', 'Bushwick Avenue–Aberdeen Street station',
                    'Broadway Junction station', 'Atlantic Avenue station',
                    'Sutter Avenue station', 'Livonia Avenue station',
                    'New Lots Avenue station', 'East 105th Street station',   
                    'Canarsie–Rockaway Parkway station',            
                ]
    },
    {
        id: '2',
        train: 'g',
        stations: [ 'Court Square','21st Street', 'Greenpoint Avenue',
                    'Nassau Avenue','Metropolitan Avenue','Broadway',
                    'Flushing Avenue','Myrtle-Willoughby Avenues',
                    'Bedford-Nostrand Avenues','Classon Avenue',
                    'Clinton-Washington Avenues','Fulton Street',
                    'Hoyt-Schermerhorn Streets','Bergen Street',
                    'Carrol Street','Smith-Ninth Streets',
                    'Fourth Avenue','Seventh Avenue station','15th Street-Prospect Park',
                    'Fort Hamilton Parkway','Church Avenue']
    },
    {
        id: '3',
        train: '1',
        stations: [ 'Van Cortlandt Park–242nd Street','238th Street','231st Street',
                    'Marble Hill–225th Street','215th Street','207th Street',
                    'Dyckman Street','191st Street','181st Street','168th Street',
                    '157th Street','145th Street','137th Street–City College',
                    '125th Street','116th Street–Columbia University',
                    'Cathedral Parkway–110th Street','103rd Street','96th Street',
                    '86th Street','79th Street','72nd Street','66th Street–Lincoln Center',
                    '59th Street–Columbus Circle','50th Street','Times Square–42nd Street',
                    '34th Street–Penn Station','28th Street','23rd Street',
                    '18th Street','14th Street','Christopher Street–Sheridan Square',
                    'Houston Street','Canal Street','Franklin Street','Chambers Street',
                    'WTC Cortlandt','Rector Street','South Ferry']
    },
    {
        id: '4',
        train: '2',
        stations: [ 'Wakefield–241st Street','Nereid Avenue','233rd Street',
                    '225th Street','219th Street','Gun Hill Road','Burke Avenue',
                    'Allerton Avenue','Pelham Parkway','Bronx Park East',
                    'East 180th Street','West Farms Square–East Tremont Avenue',
                    '174th Street','Freeman Street','Simpson Street','Intervale Avenue',
                    'Prospect Avenue','Jackson Avenue','Third Avenue–149th Street',
                    '149th Street–Grand Concourse','135th Street','125th Street',
                    '116th Street','Central Park North–110th Street','96th Street',
                    '86th Street','79th Street','72nd Street','66th Street–Lincoln Center',
                    '59th Street–Columbus Circle','50th Street','Times Square–42nd Street',
                    '34th Street–Penn Station','28th Street','23rd Street','18th Street',
                    '14th Street','Christopher Street–Sheridan Square','Houston Street',
                    'Canal Street','Franklin Street','Chambers Street','Park Place',
                    'Fulton Street','Wall Street','Clark Street','Borough Hall',
                    'Hoyt Street','Nevins Street','Atlantic Avenue–Barclays Center',
                    'Bergen Street','Grand Army Plaza','Eastern Parkway–Brooklyn Museum',
                    'Franklin Avenue–Medgar Evers College','President Street–Medgar Evers College',
                    'Sterling Street','Winthrop Street','Church Avenue','Beverly Road',
                    'Newkirk Avenue–Little Haiti','Flatbush Avenue–Brooklyn College']
    },
    {
        id: '5',
        train: '3',
        stations: [ 'Harlem–148th Street','145th Street','135th Street','125th Street',
                    '116th Street','Central Park North–110th Street','96th Street',
                    '72nd Street','Times Square–42nd Street','34th Street–Penn Station',
                    '14th Street','Chambers Street','Park Place','Fulton Street',
                    'Wall Street','Clark Street','Borough Hall','Hoyt Street',
                    'Nevins Street','Atlantic Avenue–Barclays Center','Bergen Street',
                    'Grand Army Plaza','Eastern Parkway–Brooklyn Museum',
                    'Franklin Avenue–Medgar Evers College','Nostrand Avenue',
                    'Kingston Avenue','Crown Heights–Utica Avenue','Sutter Avenue–Rutland Road',
                    'Saratoga Avenue','Rockaway Avenue','Junius Street','Pennsylvania Avenue',
                    'Van Siclen Avenue','New Lots Avenue']
    },
    {
        id: '6',
        train: '4',
        stations: [ 'Woodlawn','Mosholu Parkway','Bedford Park Boulevard–Lehman College',
                    'Kingsbridge Road','Fordham Road','183rd Street','Burnside Avenue',
                    '176th Street','Mount Eden Avenue','170th Street','167th Street',
                    '161st Street–Yankee Stadium','149th Street–Grand Concourse',
                    '138th Street–Grand Concourse','125th Street','116th Street',
                    '110th Street','103rd Street','96th Street','86th Street',
                    '77th Street','68th Street–Hunter College','59th Street',
                    '51st Street','Grand Central–42nd Street','33rd Street',
                    '28th Street','23rd Street','14th Street–Union Square',
                    'Astor Place','Bleecker Street','Spring Street','Canal Street',
                    'Brooklyn Bridge–City Hall','Fulton Street','Wall Street',
                    'Bowling Green','Borough Hall','Nevins Street',
                    'Atlantic Avenue–Barclays Center','Bergen Street',
                    'Grand Army Plaza','Eastern Parkway–Brooklyn Museum',
                    'Franklin Avenue–Medgar Evers College','Nostrand Avenue',
                    'Kingston Avenue','Crown Heights–Utica Avenue',
                    'Sutter Avenue–Rutland Road','Saratoga Avenue',
                    'Rockaway Avenue','Junius Street','Pennsylvania Avenue',
                    'Van Siclen Avenue','New Lots Avenue']
    },
    {
        id: '7',
        train: '5',
        stations: [ 'Eastchester–Dyre Avenue','Baychester Avenue','Gun Hill Road/Seymour Avenue',
                    'Pelham Parkway/Esplanade','Morris Park','Nereid Avenue','233rd Street',
                    '225th Street','219th Street','Gun Hill Road/White Plains Road',
                    'Burke Avenue','Allerton Avenue','Pelham Parkway/White Plains Road',
                    'Bronx Park East','East 180th Street','West Farms Square–East Tremont Avenue',
                    '174th Street','Freeman Street','Simpson Street','Intervale Avenue',
                    'Prospect Avenue','Jackson Avenue','Third Avenue–149th Street',
                    '149th Street–Grand Concourse','138th Street–Grand Concourse',
                    '125th Street','86th Street','59th Street','Grand Central–42nd Street',
                    '14th Street–Union Square','Brooklyn Bridge–City Hall','Fulton Street',
                    'Wall Street','Bowling Green','Borough Hall','Nevins Street',
                    'Atlantic Avenue–Barclays Center','Franklin Avenue–Medgar Evers College',
                    'President Street–Medgar Evers College','Sterling Street',
                    'Winthrop Street','Church Avenue','Beverly Road','Newkirk Avenue–Little Haiti',
                    'Flatbush Avenue–Brooklyn College','Nostrand Avenue','Kingston Avenue',
                    'Crown Heights–Utica Avenue','Sutter Avenue–Rutland Road',
                    'Saratoga Avenue','Rockaway Avenue','Junius Street',
                    'Pennsylvania Avenue','Van Siclen Avenue','New Lots Avenue']
    },
    {
        id: '8',
        train: '6',
        stations: [ "Pelham Bay Park",'Buhre Avenue','Middletown Road',
                    "Westchester Square–East Tremont Avenue","Zerega Avenue",
                    "Castle Hill Avenue","Parkchester","St. Lawrence Avenue",
                    "Morrison Avenue–Soundview","Elder Avenue","Whitlock Avenue",
                    "Hunts Point Avenue","Longwood Avenue","East 149th Street",
                    "East 143rd Street–St. Mary's Street","Cypress Avenue",
                    'Brook Avenue',"Third Avenue–138th Street",'125th Street',
                    "116th Street","110th Street","103rd Street","96th Street",
                    '86th Street','77th Street','68th Street–Hunter College',
                    "59th Street","51st Street","Grand Central–42nd Street",
                    "33rd Street","28th Street","23rd Street","14th Street–Union Square",
                    "Astor Place", "Bleecker Street", "Spring Street",
                    "Canal Street", "Brooklyn Bridge–City Hall"]
    },
    {
        id: '9',
        train: '7',
        stations: [ "Flushing–Main Street","Mets–Willets Point",'111th Street',
                    '103rd Street–Corona Plaza','Junction Boulevard',
                    '90th Street–Elmhurst Avenue','82nd Street–Jackson Heights',
                    '74th Street–Broadway', '69th Street','61st Street–Woodside',
                    '52nd Street', '46th Street–Bliss Street', '40th Street–Lowery Street',
                    '33rd Street–Rawson Street', 'Queensboro Plaza', 'Court Square',
                    'Hunters Point Avenue', 'Vernon Boulevard–Jackson Avenue',
                    'Grand Central–42nd Street', 'Fifth Avenue', 'Times Square–42nd Street',
                    "34th Street–Hudson Yards"]
    },
    {
        id: '10',
        train: 'a',
        stations: [ 'Inwood–207th Street','Dyckman Street','190th Street',
                    '181st Street','175th Street','168th Street','163rd Street–Amsterdam Avenue',
                    '155th Street','145th Street','135th Street','125th Street','116th Street',
                    'Cathedral Parkway–110th Street','103rd Street','96th Street','86th Street',
                    '81st Street–Museum of Natural History','72nd Street',
                    '59th Street–Columbus Circle','50th Street',
                    '42nd Street–Port Authority Bus Terminal','34th Street–Penn Station',
                    '23rd Street','14th Street','West Fourth Street–Washington Square',
                    'Spring Street','Canal Street','Chambers Street','Fulton Street',
                    'High Street', 'Jay Street–MetroTech','Hoyt–Schermerhorn Streets',
                    'Lafayette Avenue','Clinton–Washington Avenues','Franklin Avenue',
                    'Nostrand Avenue','Kingston–Throop Avenues','Utica Avenue',
                    'Ralph Avenue','Rockaway Avenue','Broadway Junction',
                    'Liberty Avenue','Van Siclen Avenue','Shepherd Avenue','Euclid Avenue',
                    'Grant Avenue','80th Street','88th Street','Rockaway Boulevard',
                    '104th Street','111th Street','Ozone Park–Lefferts Boulevard',
                    'Aqueduct Racetrack','Aqueduct–North Conduit Avenue',
                    'Howard Beach–JFK Airport','Broad Channel','Beach 67th Street',
                    'Beach 60th Street','Beach 44th Street','Beach 36th Street',
                    'Beach 25th Street','Far Rockaway–Mott Avenue','Beach 90th Street',
                    'Beach 98th Street','Beach 105th Street','Rockaway Park–Beach 116th Street']
    },
    {
        id: '11',
        train: 'b',
        stations: [ 'Bedford Park Boulevard','Kingsbridge Road','Fordham Road',
                    '182nd–183rd Streets','Tremont Avenue','174th–175th Streets',
                    '170th Street','167th Street','161st Street–Yankee Stadium',
                    '155th Street','145th Street','135th Street','125th Street',
                    '116th Street','Cathedral Parkway–110th Street','103rd Street',
                    '96th Street','86th Street','81st Street–Museum of Natural History',
                    '72nd Street','59th Street–Columbus Circle','Seventh Avenue/53rd Street',
                    '47th–50th Streets–Rockefeller Center','42nd Street–Bryant Park',
                    '34th Street–Herald Square','West Fourth Street–Washington Square',
                    'Broadway–Lafayette Street','Grand Street','DeKalb Avenue',
                    'Atlantic Avenue–Barclays Center','Seventh Avenue/Flatbush Avenue',
                    'Prospect Park','Church Avenue','Newkirk Plaza', 'Kings Highway',
                    'Kings Highway','Brighton Beach']
    },
    {
        id: '12',
        train: 'c',
        stations: [ '168th Street','163rd Street–Amsterdam Avenue','155th Street',
                    '145th Street','135th Street','125th Street','116th Street',
                    'Cathedral Parkway–110th Street', '103rd Street','96th Street',
                    '86th Street','81st Street–Museum of Natural History',
                    '72nd Street','59th Street–Columbus Circle','50th Street',
                    '42nd Street–Port Authority Bus Terminal','34th Street–Penn Station',
                    '23rd Street','14th Street','West Fourth Street–Washington Square',
                    'Spring Street','Canal Street','Chambers Street','Fulton Street',
                    'High Street','Jay Street–MetroTech','Hoyt–Schermerhorn Streets',
                    'Lafayette Avenue','Clinton–Washington Avenues','Franklin Avenue',
                    'Nostrand Avenue','Kingston–Throop Avenues','Utica Avenue',
                    'Ralph Avenue','Rockaway Avenue','Broadway Junction',
                    'Liberty Avenue','Van Siclen Avenue','Shepherd Avenue',
                    'Euclid Avenue']
    },
    {
        id: '13',
        train: 'd',
        stations: [ 'Norwood–205th Street','Bedford Park Boulevard','Kingsbridge Road',
                    'Fordham Road','182nd–183rd Streets','Tremont Avenue',
                    '174th–175th Streets','170th Street','167th Street',
                    '161st Street–Yankee Stadium','155th Street','145th Street',
                    '125th Street','59th Street–Columbus Circle','Seventh Avenue',
                    '47th–50th Streets–Rockefeller Center','42nd Street–Bryant Park',
                    '34th Street–Herald Square','West Fourth Street–Washington Square',
                    'Broadway–Lafayette Street','Grand Street','DeKalb Avenue',
                    'Atlantic Avenue–Barclays Center','Union Street',
                    'Ninth Street','Prospect Avenue','25th Street',
                    '36th Street','Ninth Avenue','Fort Hamilton Parkway','50th Street',
                    '55th Street','62nd Street','71st Street','79th Street',
                    '18th Avenue','20th Avenue','Bay Parkway','25th Avenue',
                    'Bay 50th Street','Coney Island–Stillwell Avenue' ]
    },
    {
        id: '14',
        train: 'e',
        stations: [ 'Jamaica–179th Street','169th Street','Parsons Boulevard',
                    'Sutphin Boulevard/Hillside Avenue','Jamaica Center–Parsons/Archer',
                    'Sutphin Boulevard–Archer Avenue–JFK Airport','Jamaica–Van Wyck',
                    'Briarwood','Kew Gardens–Union Turnpike','75th Avenue',
                    'Forest Hills–71st Avenue','67th Avenue','63rd Drive–Rego Park',
                    'Woodhaven Boulevard','Grand Avenue–Newtown','Elmhurst Avenue',
                    'Jackson Heights–Roosevelt Avenue','65th Street','Northern Boulevard',
                    '46th Street','Steinway Street','36th Street','Queens Plaza',
                    'Court Square–23rd Street','Lexington Avenue–53rd Street',
                    'Fifth Avenue/53rd Street','Seventh Avenue','50th Street',
                    '42nd Street–Port Authority Bus Terminal','34th Street–Penn Station',
                    '23rd Street','14th Street','West Fourth Street–Washington Square',
                    'Spring Street','Canal Street','World Trade Center' ]
    },
    {
        id: '15',
        train: 'f',
        stations: [ 'Jamaica–179th Street','169th Street','Parsons Boulevard',
                    'Sutphin Boulevard','Briarwood','Kew Gardens–Union Turnpike',
                    '75th Avenue','Forest Hills–71st Avenue',
                    'Jackson Heights–Roosevelt Avenue','21st Street–Queensbridge',
                    'Roosevelt Island','Lexington Avenue–63rd Street',
                    '57th Street','47th–50th Streets–Rockefeller Center',
                    '42nd Street–Bryant Park','34th Street–Herald Square',
                    '23rd Street','14th Street',
                    'West Fourth Street–Washington Square','Broadway–Lafayette Street',
                    'Second Avenue','Delancey Street','East Broadway',
                    'York Street','Jay Street–MetroTech','Bergen Street',
                    'Carroll Street','Smith–Ninth Streets',
                    'Fourth Avenue','Seventh Avenue','15th Street–Prospect Park',
                    'Fort Hamilton Parkway','Church Avenue','Ditmas Avenue',
                    '18th Avenue','Avenue I','Bay Parkway','Avenue N','Avenue P',
                    'Kings Highway','Avenue U','Avenue X','Neptune Avenue',
                    'West Eighth Street–New York Aquarium','Coney Island–Stillwell Avenue' ]
    },
    {
        id: '16',
        train: 'j',
        stations: [ 'Jamaica Center–Parsons/Archer','Sutphin Boulevard–Archer Avenue–JFK Airport',
                    '121st Street','111th Street','104th Street','Woodhaven Boulevard',
                    '85th Street–Forest Parkway','75th Street–Elderts Lane',
                    'Cypress Hills','Crescent Street','Norwood Avenue','Cleveland Street',
                    'Van Siclen Avenue','Alabama Avenue','Broadway Junction',
                    'Chauncey Street','Halsey Street','Gates Avenue','Kosciuszko Street',
                    'Myrtle Avenue–Broadway','Flushing Avenue','Lorimer Street',
                    'Hewes Street','Marcy Avenue','Essex Street','Bowery','Canal Street',
                    'Chambers Street','Fulton Street','Broad Street' ]
    },
    {
        id: '17',
        train: 'm',
        stations: [ 'Forest Hills–71st Avenue','67th Avenue','63rd Drive–Rego Park',
                    'Woodhaven Boulevard','Grand Avenue–Newtown','Elmhurst Avenue',
                    'Jackson Heights–Roosevelt Avenue','65th Street','Northern Boulevard',
                    '46th Street','Steinway Street','36th Street','Queens Plaza',
                    'Court Square–23rd Street','Lexington Avenue–53rd Street',
                    'Fifth Avenue/53rd Street','47th–50th Streets–Rockefeller Center',
                    '42nd Street–Bryant Park','34th Street–Herald Square','23rd Street',
                    '14th Street','West Fourth Street–Washington Square',
                    'Broadway–Lafayette Street','Essex Street','Marcy Avenue','Hewes Street',
                    'Lorimer Street','Flushing Avenue','Myrtle Avenue–Broadway',
                    'Central Avenue','Knickerbocker Avenue','Myrtle–Wyckoff Avenues',
                    'Seneca Avenue','Forest Avenue','Fresh Pond Road', 
                    'Middle Village–Metropolitan Avenue' ]
    },
    {
        id: '18',
        train: 'n',
        stations: [ '96th Street','86th Street/Second Avenue','72nd Street',
                    'Lexington Avenue–63rd Street','Astoria–Ditmars Boulevard',
                    'Astoria Boulevard','30th Avenue','Broadway','36th Avenue',
                    '39th Avenue','Queensboro Plaza','Lexington Avenue/59th Street',
                    'Fifth Avenue–59th Street','57th Street–Seventh Avenue',
                    '49th Street','Times Square–42nd Street','34th Street–Herald Square',
                    '28th Street','23rd Street','14th Street–Union Square',
                    'Eighth Street–New York University','Prince Street',
                    'Canal Street–Broadway','Canal Street','City Hall',
                    'Cortlandt Street','Rector Street','Whitehall Street–South Ferry',
                    'Court Street','Jay Street–MetroTech','DeKalb Avenue',
                    'Atlantic Avenue–Barclays Center','Union Street','Ninth Street',
                    'Prospect Avenue','25th Street','36th Street',
                    '45th Street','53rd Street','59th Street/Fourth Avenue',
                    'Eighth Avenue','Fort Hamilton Parkway',
                    'New Utrecht Avenue','18th Avenue',
                    '20th Avenue','Bay Parkway','Kings Highway','Avenue U',
                    'Gravesend–86th Street','Coney Island–Stillwell Avenue' ]
    },
    {
        id: '19',
        train: 'q',
        stations: [ '96th Street','86th Street/Second Avenue','72nd Street',
                    'Lexington Avenue–63rd Street','57th Street–Seventh Avenue',
                    '49th Street','Times Square–42nd Street','34th Street–Herald Square',
                    '28th Street','23rd Street','14th Street–Union Square',
                    'Eighth Street–New York University','Prince Street','Canal Street',
                    'DeKalb Avenue','Atlantic Avenue–Barclays Center','Seventh Avenue',
                    'Prospect Park','Parkside Avenue','Church Avenue','Beverley Road',
                    'Cortelyou Road','Newkirk Plaza','Avenue H','Avenue J','Avenue M',
                    'Kings Highway','Avenue U','Neck Road','Sheepshead Bay',
                    'Brighton Beach','Ocean Parkway',
                    'West Eighth Street–New York Aquarium',
                    'Atlantic Avenue–Barclays Center','36th Street','59th Street',
                    'Eighth Avenue','Fort Hamilton Parkway','New Utrecht Avenue',
                    '18th Avenue','20th Avenue','Bay Parkway','Kings Highway',
                    'Avenue U','Gravesend–86th Street','Coney Island–Stillwell Avenue' ]
    },
    {
        id: '20',
        train: 'r',
        stations: [ '96th Street','86th Street/Second Avenue','72nd Street',
                    'Lexington Avenue–63rd Street','Forest Hills–71st Avenue',
                    '67th Avenue','63rd Drive–Rego Park','Woodhaven Boulevard',
                    'Grand Avenue–Newtown','Elmhurst Avenue',
                    'Jackson Heights–Roosevelt Avenue','65th Street',
                    'Northern Boulevard','46th Street','Steinway Street',
                    '36th Street/Northern Boulevard','Queens Plaza',
                    'Lexington Avenue/59th Street','Fifth Avenue–59th Street',
                    '57th Street–Seventh Avenue','49th Street',
                    'Times Square–42nd Street','34th Street–Herald Square',
                    '28th Street','23rd Street','14th Street–Union Square',
                    'Eighth Street–New York University','Prince Street',
                    'Canal Street','City Hall','Cortlandt Street','Rector Street',
                    'Whitehall Street–South Ferry','Court Street','Jay Street–MetroTech',
                    'DeKalb Avenue','Atlantic Avenue–Barclays Center',
                    'Union Street','Ninth Street','Prospect Avenue','25th Street',
                    '36th Street/Fourth Avenue','45th Street','53rd Street',
                    '59th Street/Fourth Avenue','Bay Ridge Avenue','77th Street',
                    '86th Street/Fourth Avenue','Bay Ridge–95th Street' ]
    },
    {
        id: '21',
        train: 'z',
        stations: [ 'Jamaica Center–Parsons/Archer','Sutphin Boulevard–Archer Avenue–JFK Airport',
                    '121st Street','111th Street','104th Street','Woodhaven Boulevard',
                    '85th Street–Forest Parkway','75th Street–Elderts Lane','Cypress Hills',
                    'Crescent Street','Norwood Avenue','Cleveland Street',
                    'Van Siclen Avenue','Alabama Avenue','Broadway Junction',
                    'Chauncey Street','Halsey Street','Gates Avenue','Kosciuszko Street',
                    'Myrtle Avenue–Broadway', 'Flushing Avenue','Lorimer Street',
                    'Hewes Street','Marcy Avenue' ]
    },
    

]
