export default [ 
    {
        id: '1',
        train: 'l',
        stations: [ '14 Street Union Square Station','Third Avenue station','First Avenue station',
                    'Bedford Avenue station''Graham Avenue station','Grand Street station',
                    'Montrose Avenue station','Morgan Avenue station',
                    'Jefferson Street station', 'DeKalb Avenue station',
                    'Myrtle–Wyckoff Avenues station', 'Halsey Street station',
                    'Wilson Avenue station', 'Bushwick Avenue–Aberdeen Street station',
                    'Broadway Junction station', 'Atlantic Avenue station',
                    'Sutter Avenue station', 'Livonia Avenue station',
                    'New Lots Avenue station', 'East 105th Street station',   
                    'Canarsie–Rockaway Parkway station',            
                ]
    },
    {
        id: '2',
        train: 'g',
        stations: [ 'Court Square–23rd Street station','21st Street station', 'Greenpoint Avenue station',
                    'Nassau Avenue station','Metropolitan Avenue-Lorimer Street station','Broadway station',
                    'Flushing Avenue station','Myrtle–Willoughby Avenues station',
                    'Bedford–Nostrand Avenues station','Classon Avenue station',
                    'Clinton–Washington Avenues station','Fulton Street station',
                    'Hoyt–Schermerhorn Streets station','Bergen Street station',
                    'Carroll Street station','Smith–Ninth Streets station',
                    'Seventh Avenue station','15th Street–Prospect Park station',
                    'Fort Hamilton Parkway station','Church Avenue station']
    },
    {
        id: '3',
        train: '1',
        stations: [ 'Van Cortlandt Park–242nd Street station','238th Street station','231st Street station',
                    'Marble Hill–225th Street station','215th Street station','207th Street station',
                    'Dyckman Street station','191st Street station','181st Street station','168th Street station',
                    '157th Street station','145th Street station','137th Street–City College station',
                    '125th Street station','116th Street–Columbia University station',
                    'Cathedral Parkway–110th Street station','103rd Street station','96th Street station',
                    '86th Street station','79th Street station','72nd Street station','66th Street–Lincoln Center station',
                    '59th Street–Columbus Circle station','50th Street station','Times Square–42nd Street–Port Authority Bus Terminal station',
                    '34th Street–Penn Station','28th Street station','23rd Street station',
                    '18th Street station','14th Street-Sixth Avenue station','Christopher Street–Sheridan Square station',
                    'Houston Street station','Canal Street station','Franklin Street station',
                    'WTC Cortlandt station','Rector Street station','South Ferry–Whitehall Street station']
    },
    {
        id: '4',
        train: '2',
        stations: [ 'Wakefield–241st Street station','Nereid Avenue station','233rd Street station',
                    '225th Street station','219th Street station','Burke Avenue station',
                    'Allerton Avenue station','Pelham Parkway station','Bronx Park East station',
                    'East 180th Street station','West Farms Square–East Tremont Avenue station',
                    '174th Street station','Freeman Street station','Simpson Street station','Intervale Avenue station',
                    'Prospect Avenue station','Jackson Avenue station','Third Avenue–149th Street station',
                    '149th Street–Grand Concourse station','135th Street station','125th Street station',
                    '116th Street station','Central Park North–110th Street station','96th Street station',
                    '72nd Street station','Times Square–42nd Street–Port Authority Bus Terminal station',
                    '34th Street–Penn Station','14th Street-Sixth Avenue station', 'Chambers Street station',
                    'Fulton Street station','Wall Street station','Clark Street station','Borough Hall–Court Street station',
                    'Hoyt Street station','Nevins Street station','Atlantic Avenue–Barclays Center station',
                    'Bergen Street station','Grand Army Plaza station','Eastern Parkway–Brooklyn Museum station',
                    'Franklin Avenue station','President Street–Medgar Evers College station',
                    'Sterling Street station','Winthrop Street station','Church Avenue station','Beverly Road station',
                    'Newkirk Avenue–Little Haiti station','Flatbush Avenue–Brooklyn College station']
    },
{
        id: '5',
        train: '3',
        stations: [ 'Harlem–148th Street station','145th Street station','135th Street station','125th Street station',
                    '116th Street station','Central Park North–110th Street station','96th Street station',
                    '72nd Street station','Times Square–42nd Street–Port Authority Bus Terminal station','34th Street–Penn Station',
                    '14th Street-Sixth Avenue station','Chambers Street station','Fulton Street station',
                    'Wall Street station','Clark Street station','Borough Hall–Court Street station','Hoyt Street station',
                    'Nevins Street station','Atlantic Avenue–Barclays Center station','Bergen Street station',
                    'Grand Army Plaza station','Eastern Parkway–Brooklyn Museum station',
                    'Franklin Avenue station','Nostrand Avenue station',
                    'Kingston Avenue station','Crown Heights–Utica Avenue station','Sutter Avenue–Rutland Road station',
                    'Saratoga Avenue station','Rockaway Avenue station','Junius Street station','Pennsylvania Avenue station',
                    'Van Siclen Avenue station','New Lots Avenue station']
    },
    {
        id: '6',
        train: '4',
        stations: [ 'Woodlawn station','Mosholu Parkway station','Bedford Park Boulevard–Lehman College station',
                    'Kingsbridge Road station','Fordham Road station','183rd Street station','Burnside Avenue station',
                    '176th Street station','Mount Eden Avenue station','170th Street station','167th Street station',
                    '161st Street–Yankee Stadium station','149th Street–Grand Concourse station',
                    '138th Street–Grand Concourse station','125th Street station','86th Street station',
                    'Lexington Avenue–59th Street station','Grand Central–42nd Street station','14 Street Union Square Station',
                    'Brooklyn Bridge–City Hall–Chambers Street station','Fulton Street station','Wall Street station',
                    'Bowling Green station','Borough Hall–Court Street station','Nevins Street station',
                    'Atlantic Avenue–Barclays Center station','Franklin Avenue station','Crown Heights–Utica Avenue station']
    },
    {
        id: '7',
        train: '5',
        stations: [ 'Eastchester–Dyre Avenue station','Baychester Avenue station','Gun Hill Road–Seymour Avenue station',
                    'Pelham Parkway station','Morris Park station','Nereid Avenue station','233rd Street station',
                    '225th Street station','219th Street station','Gun Hill Road–White Plains Road station',
                    'Burke Avenue station','Allerton Avenue station','Pelham Parkway–White Plains Road station',
                    'Bronx Park East station','East 180th Street station','West Farms Square–East Tremont Avenue station',
                    '174th Street station','Freeman Street station','Simpson Street station','Intervale Avenue station',
                    'Prospect Avenue station','Jackson Avenue station','Third Avenue–149th Street station',
                    '149th Street–Grand Concourse station','138th Street–Grand Concourse station',
                    '125th Street station','86th Street station','Lexington Avenue–59th Street station','Grand Central–42nd Street station',
                    '14 Street Union Square Station','Brooklyn Bridge–City Hall–Chambers Street station','Fulton Street station',
                    'Wall Street station','Bowling Green station','Borough Hall–Court Street station','Nevins Street station',
                    'Atlantic Avenue–Barclays Center station','Franklin Avenue station',
                    'President Street–Medgar Evers College station','Sterling Street station',
                    'Winthrop Street station','Church Avenue station','Beverly Road station','Newkirk Avenue–Little Haiti station',
                    'Flatbush Avenue–Brooklyn College station']
    },
    {
        id: '8',
        train: '6',
        stations: [ 'Pelham Bay Park station','Buhre Avenue station','Middletown Road station',
                    'Westchester Square–East Tremont Avenue station','Zerega Avenue station',
                    'Castle Hill Avenue station','Parkchester station','St. Lawrence Avenue station',
                    'Morrison Avenue–Soundview station','Elder Avenue station','Whitlock Avenue station',
                    'Hunts Point Avenue station','Longwood Avenue station','East 149th Street station',
                    'East 143rd Street station','Cypress Avenue station',
                    'Brook Avenue station','Third Avenue–138th Street station','125th Street station',
                    '116th Street station','110th Street station','103rd Street station','96th Street station',
                    '86th Street station','77th Street station','68th Street–Hunter College station',
                    'Lexington Avenue–59th Street station','Lexington Avenue–51st Street station','Grand Central–42nd Street station',
                    '33rd Street station','28th Street station','23rd Street station','14 Street Union Square Station',
                    'Astor Place station', 'Bleecker Street station', 'Spring Street station',
                    'Canal Street station', 'Brooklyn Bridge–City Hall–Chambers Street station']
    },
    {
        id: '9',
        train: '7',
        stations: [ 'Flushing–Main Street station','Mets–Willets Point station','111th Street station',
                    '103rd Street–Corona Plaza station','Junction Boulevard station',
                    '90th Street–Elmhurst Avenue station','Jackson Heights–Roosevelt Avenue–74th Street station',
                    '82nd Street–Jackson Heights station','69th Street station','61st Street–Woodside station',
                    '52nd Street station', '46th Street–Bliss Street station', '40th Street–Lowery Street station',
                    '33rd Street–Rawson Street station', 'Queensboro Plaza station', 'Court Square–23rd Street station',
                    'Hunters Point Avenue station', 'Vernon Boulevard–Jackson Avenue station',
                    'Grand Central–42nd Street station', 'Fifth Avenue station', 'Times Square–42nd Street–Port Authority Bus Terminal station',
                    '34th Street–Hudson Yards station']
    },
    {
        id: '10',
        train: 'a',
        stations: [ 'Inwood–207th Street station','Dyckman Street station','190th Street station',
                    '181st Street station','175th Street station','168th Street station',
                    '145th Street station','125th Street station','59th Street–Columbus Circle station',
                    'Times Square–42nd Street–Port Authority Bus Terminal station','34th Street–Penn Station',
                    '14th Street-Eighth Avenue station','West Fourth Street–Washington Square station',
                    'Canal Street station','Chambers Street station','Fulton Street station',
                    'High Street station', 'Jay Street–MetroTech station','Hoyt–Schermerhorn Streets station',
                    'Nostrand Avenue station','Utica Avenue station','Broadway Junction station',
                    'Euclid Avenue station',
                    'Grant Avenue station','80th Street station','88th Street station','Rockaway Boulevard station',
                    '104th Street station','111th Street station','Ozone Park–Lefferts Boulevard station',
                    'Aqueduct Racetrack station','Aqueduct–North Conduit Avenue station',
                    'Howard Beach–JFK Airport station','Broad Channel station','Beach 67th Street station',
                    'Beach 60th Street station','Beach 44th Street station','Beach 36th Street station',
                    'Beach 25th Street station','Far Rockaway–Mott Avenue station']
    },
    {
        id: '11',
        train: 'b',
        stations: [ 'Bedford Park Boulevard station','Kingsbridge Road station','Fordham Road station',
                    '182nd–183rd Streets station','Tremont Avenue station','174th–175th Streets station',
                    '170th Street station','167th Street station','161st Street–Yankee Stadium station',
                    '155th Street station','145th Street station','135th Street station','125th Street station',
                    '116th Street station','Cathedral Parkway–110th Street station','103rd Street station',
                    '96th Street station','86th Street station','81st Street–Museum of Natural History station',
                    '72nd Street station','59th Street–Columbus Circle station','Seventh Avenue–53rd Street station',
                    '47th–50th Streets–Rockefeller Center station','Sheepshead Bay station',
                    '34th Street–Herald Square station','West Fourth Street–Washington Square station',
                    'Fifth Avenue station','Grand Street station','DeKalb Avenue station',
                    'Atlantic Avenue–Barclays Center station','Seventh Avenue–Flatbush Avenue station',
                    'Prospect Park station','Church Avenue station','Newkirk Plaza station', 'Kings Highway station',
                    'Bleecker Street station','Brighton Beach station']
    },
    {
        id: '12',
        train: 'c',
        stations: [ '168th Street station','163rd Street–Amsterdam Avenue station','155th Street station',
                    '145th Street station','135th Street station','125th Street station','116th Street station',
                    'Cathedral Parkway–110th Street station', '103rd Street station','96th Street station',
                    '86th Street station','81st Street–Museum of Natural History station',
                    '72nd Street station','59th Street–Columbus Circle station','50th Street station',
                    'Times Square–42nd Street–Port Authority Bus Terminal station','34th Street–Penn Station',
                    '23rd Street station','14th Street-Eighth Avenue station','West Fourth Street–Washington Square station',
                    'Spring Street station','Canal Street station','Chambers Street station','Fulton Street station',
                    'High Street station','Jay Street–MetroTech station','Hoyt–Schermerhorn Streets station',
                    'Lafayette Avenue station','Clinton–Washington Avenues station','Franklin Avenue station',
                    'Nostrand Avenue station','Kingston–Throop Avenues station','Utica Avenue station',
                    'Ralph Avenue station','Rockaway Avenue station','Broadway Junction station',
                    'Liberty Avenue station','Van Siclen Avenue station','Shepherd Avenue station',
                    'Euclid Avenue station']
    },
    {
        id: '13',
        train: 'd',
        stations: [ 'Norwood–205th Street station','Bedford Park Boulevard station','Kingsbridge Road station',
                    'Fordham Road station','182nd–183rd Streets station','Tremont Avenue station',
                    '174th–175th Streets station','170th Street station','167th Street station',
                    '161st Street–Yankee Stadium station','155th Street station','145th Street station',
                    '125th Street station','59th Street–Columbus Circle station','Seventh Avenue–53rd Street station',
                    '47th–50th Streets–Rockefeller Center station','42nd Street–Bryant Park station',
                    '34th Street–Herald Square station','West Fourth Street–Washington Square station',
                    'Grand Street station', 'Fifth Avenue station', 'Bleecker Street station',
                    'Atlantic Avenue–Barclays Center station',
                    '36th Street station','Ninth Avenue station','Fort Hamilton Parkway station','50th Street station',
                    '55th Street station','62nd Street station','71st Street station','79th Street station',
                    '18th Avenue station','20th Avenue station','Bay Parkway station','25th Avenue station',
                    'Bay 50th Street station','Coney Island–Stillwell Avenue station' ]
    },
    {
        id: '14',
        train: 'e',
        stations: [ 'Jamaica Center–Parsons–Archer station','Sutphin Boulevard–Archer Avenue–JFK Airport station',
                    'Jamaica–Van Wyck station','Briarwood station','Kew Gardens–Union Turnpike station',
                    '75th Avenue station','Forest Hills–71st Avenue station','Jackson Heights–Roosevelt Avenue–74th Street station',
                    'Queens Plaza station','Court Square–23rd Street station','Lexington Avenue–51st Street station',
                    'Fifth Avenue–53rd Street station','Seventh Avenue–53rd Street station','50th Street station',
                    'Times Square–42nd Street–Port Authority Bus Terminal station','34th Street–Penn Station',
                    '23rd Street station','14th Street-Eighth Avenue station','West Fourth Street–Washington Square station',
                    'Spring Street station','Canal Street station']
    },
    {
        id: '15',
        train: 'f',
        stations: [ 'Jamaica–179th Street station','169th Street station','Parsons Boulevard station',
                    'Sutphin Boulevard station','Briarwood station','Kew Gardens–Union Turnpike station',
                    '75th Avenue station','Forest Hills–71st Avenue station',
                    'Jackson Heights–Roosevelt Avenue–74th Street station','21st Street–Queensbridge station',
                    'Roosevelt Island station','Lexington Avenue–63rd Street station',
                    '57th Street station','47th–50th Streets–Rockefeller Center station',
                    '34th Street–Herald Square station','23rd Street station','14th Street-Sixth Avenue station',
                    'West Fourth Street–Washington Square station',
                    'Second Avenue station','Delancey Street station','East Broadway station',
                    'York Street station','Jay Street–MetroTech station','Bergen Street station',
                    'Carroll Street station','Smith–Ninth Streets station',
                    'Fourth Avenue-Ninth Street station','Seventh Avenue station','15th Street–Prospect Park station',
                    'Fort Hamilton Parkway station','Church Avenue station','Ditmas Avenue station',
                    '18th Avenue station','Avenue I station','Bay Parkway station','Avenue N station','Avenue P station',
                    'Kings Highway station','Avenue U station','Avenue X station','Neptune Avenue station',
                    'West Eighth Street–New York Aquarium station','Coney Island–Stillwell Avenue station' ]
    },
    {
        id: '16',
        train: 'j',
        stations: [ 'Jamaica Center–Parsons–Archer station','Sutphin Boulevard–Archer Avenue–JFK Airport station',
                    '121st Street station','104th Street station','Woodhaven Boulevard station',
                    '85th Street–Forest Parkway station','75th Street–Elderts Lane station',
                    'Cypress Hills station','Crescent Street station','Norwood Avenue station','Cleveland Street station',
                    'Van Siclen Avenue station','Alabama Avenue station','Broadway Junction station',
                    'Chauncey Street station','Halsey Street station','Gates Avenue station','Kosciuszko Street station',
                    'Myrtle Avenue station','Flushing Avenue station','Lorimer Street station',
                    'Hewes Street station','Marcy Avenue station','Bowery station','Canal Street station',
                    'Fulton Street station','Broad Street station' ]
    },
    {
        id: '17',
        train: 'm',
        stations: [ 'Forest Hills–71st Avenue station','67th Avenue station','63rd Drive–Rego Park station',
                    'Woodhaven Boulevard station','Grand Avenue–Newtown station','Elmhurst Avenue station',
                    'Jackson Heights–Roosevelt Avenue–74th Street station','65th Street station','Northern Boulevard station',
                    '46th Street station','Steinway Street station','36th Street station','Queens Plaza station',
                    'Court Square–23rd Street station','Lexington Avenue–51st Street station',
                    'Fifth Avenue station','47th–50th Streets–Rockefeller Center station',
                    '42nd Street–Bryant Park station','34th Street–Herald Square station','23rd Street station',
                    '14th Street-Sixth Avenue station','West Fourth Street–Washington Square station',
                    'Marcy Avenue station','Hewes Street station',
                    'Lorimer Street station','Flushing Avenue station','Myrtle Avenue station',
                    'Central Avenue station','Knickerbocker Avenue station','Myrtle–Wyckoff Avenues station',
                    'Seneca Avenue station','Forest Avenue station','Fresh Pond Road station', 
                    'Middle Village–Metropolitan Avenue station' ]
    },
    {
        id: '18',
        train: 'n',
        stations: [ 'Astoria–Ditmars Boulevard station',
                    'Astoria Boulevard station','30th Avenue station','Broadway station','36th Avenue station',
                    '39th Avenue station','Queensboro Plaza station','Lexington Avenue–59th Street station',
                    'Fifth Avenue–59th Street station','57th Street–Seventh Avenue station',
                    '49th Street station','Times Square–42nd Street–Port Authority Bus Terminal station','34th Street–Herald Square station',
                    '14 Street Union Square Station','Canal Street station','Atlantic Avenue–Barclays Center station',
                    'Eighth Avenue station','Fort Hamilton Parkway station','18th Avenue station',
                    '20th Avenue station','Bay Parkway station','Kings Highway station','Avenue U station',
                    '86th Street station','Coney Island–Stillwell Avenue station' ]
    },
    {
        id: '19',
        train: 'q',
        stations: [ '96th Street station','86th Street station','72nd Street station',
                    'Lexington Avenue–63rd Street station','57th Street–Seventh Avenue station',
                    'Times Square–42nd Street–Port Authority Bus Terminal station','34th Street–Herald Square station',
                    '14 Street Union Square Station',
                    'Atlantic Avenue–Barclays Center station',
                    'Prospect Park station','Parkside Avenue station','Church Avenue station','Beverley Road station',
                    'Cortelyou Road station','Newkirk Plaza station','Avenue H station','Avenue J station','Avenue M station',
                    'Kings Highway station','Avenue U station','Neck Road station','Sheepshead Bay station',
                    'Brighton Beach station','Ocean Parkway station',
                    'West Eighth Street–New York Aquarium station','Coney Island–Stillwell Avenue station' ]
    },
    {
        id: '20',
        train: 'r',
        stations: [ 'Forest Hills–71st Avenue station',
                    '67th Avenue station','63rd Drive–Rego Park station','Woodhaven Boulevard station',
                    'Grand Avenue–Newtown station','Elmhurst Avenue station',
                    'Jackson Heights–Roosevelt Avenue–74th Street station','65th Street station',
                    'Northern Boulevard station','46th Street station','Steinway Street station',
                    '36th Street–Northern Boulevard station','Queens Plaza station',
                    'Lexington Avenue–59th Street station','Fifth Avenue–59th Street station',
                    '57th Street–Seventh Avenue station','49th Street station',
                    'Times Square–42nd Street–Port Authority Bus Terminal station','34th Street–Herald Square station',
                    '28th Street station','14 Street Union Square Station',
                    'Eighth Street–New York University station','Prince Street station',
                    'Canal Street station','City Hall station','Rector Street station','Jay Street–MetroTech station',
                    'DeKalb Avenue station','Atlantic Avenue–Barclays Center station',
                    'Union Street station','Fourth Avenue-Ninth Street station','Prospect Avenue station','25th Street station',
                    '36th Street–Fourth Avenue station','45th Street station','Bay Ridge Avenue station',
                    '77th Street station','86th Street station','Bay Ridge–95th Street station' ]
    },
    {
        id: '21',
        train: 'z',
        stations: [ 'Jamaica Center–Parsons–Archer station','Sutphin Boulevard–Archer Avenue–JFK Airport station',
                    '121st Street station','104th Street station','Woodhaven Boulevard station',
                    'Crescent Street station','Norwood Avenue station',
                    'Van Siclen Avenue station','Alabama Avenue station','Broadway Junction station',
                    'Chauncey Street station','Gates Avenue station',
                    'Myrtle Avenue station', 'Marcy Avenue station' ]
    },
    

]
